### ISSUE TITLE
Error when using headless Google Chrome 61.0.3163.91

### ISSUE THREAD

**Issue by Altareq** [sjitech/proxy-login-automator#10]
Hi,

I am trying it with google chrome headless with option `--proxy-server` and i get this error and the local forwarding proxies hangs with exception below.  Any idea what can it be? or is this not supposed to work with latest google chrome and chromedriver, tests performed on an Ubuntu 14.04 LTS

```
proxy-login-automator.js:158
        parser.close();
               ^
TypeError: Object #<HTTPParser> has no method 'close'
    at Socket.cleanup (/usr/local/lib/node_modules/proxy-login-automator/proxy-login-automator.js:158:16)
    at Socket.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
```

thanks and regards

**Comment by jjqq2013** [comment]
Hi, would you tell me your nodejs version?

2017年9月18日(月) 2:29 Altareq <notifications@github.com>:

**Comment by Altareq** [comment]
Hi, here they are. thanks
```
node -v
v0.10.25
```
```
npm -v
1.3.10
```

**Comment by jjqq2013** [comment]
Thanks, i will take a look later as soon as possible (today is holiday).

2017年9月18日(月) 16:35 Altareq <notifications@github.com>:

**Comment by jjqq2013** [comment]
@Altareq hi, sorry for so late.  I got it. It is because this tool use a private API of Node.js "HttpParser",  unfortunately, your Node.js is too old so it has no such API.

You'd better upgrade your Node.js to latest? or some newer version, i am not sure.

Regards

**Comment by hamzaahmad** [comment]
try nightmare js for headless browser

**Comment by jjqq2013** [comment]
This tool is written in Jan 2015, so the minimum version it support is 0.10.36.
