### ISSUE TITLE
chrome unable to access localhost site when using proxy-login-automator as proxy server

### ISSUE THREAD

**Issue by ZodsPlan** [sjitech/proxy-login-automator#11]
Awesome work!  Thank you!! I ran into one issue...

I want to access http://localhost:3000 with google chrome (i'm running a local web application)...

I set google chrome's proxy server to the proxy-login-automator server.  When I attempt to go to the "http://localhost:3000" in the browser, a popup occurs asking for authentication from "cfauth.com" 

Any ideas?  Keep up the great work!

**Comment by jjqq2013** [comment]
Thanks for your feedback.

Are you using PAC?

You can specify a bypass list in chrome command line to avoid using proxy
for localhost.

Regards

2017年11月29日(水) 0:58 ZodsPlan <notifications@github.com>:

**Comment by ZodsPlan** [comment]
Thanks for the feedback.  I am not sure if I am using PAC.  To my understanding, PAC would be something configured at the server level?  In that case, I am behind a corporate proxy so I do not have access to those configurations.  I tried to specify --proxy-bypass-list="localhost:3000" and --proxy-bypass-list="localhost" with no luck.

**Comment by jjqq2013** [comment]
You can check who is listening at port 3000, just by “netstat -an”  or
similar linux cmd, it might exists two or more processes catching 3000, and
some listen the ipv6, some ipv4, so maybe an application happened to listen
3000 it overrided the existing one which really needed to do underline
proxy work.

2017年12月7日(木) 0:10 ZodsPlan <notifications@github.com>:

**Comment by jjqq2013** [comment]
Also check 8080 etc.

2017年12月7日(木) 8:16 Jin Qian <osexp2003@gmail.com>:

**Comment by ZodsPlan** [comment]
The PAC solution worked.  I found out the PAC file being used here and configured everything according to your instructions for the PAC file.  Worked like a charm.  Good work!  Thank you.
