### ISSUE TITLE
楼主可以做到集成pac文件中来解决这个自动登录认证的问题？

### ISSUE THREAD

**Issue by 1265578519** [sjitech/proxy-login-automator#2]
谷歌查了很多资料，都没有这方面的文档。
用户名:密码@ip:端口这样也不行。
var proxy = "PROXY server01.pac.itzmx.com:25;";
现在是这样
然后打开浏览器必须输入登录框认证，这就存在了app，谷歌浏览器翻译功能无法使用等问题，能否在pac文件中直接控制这个自动登录？
http://pac.itzmx.com

**Comment by QianJin2013** [comment]
这个工具就是为了这个目的而做的，支持pac。对于像我一样有强迫症的人，可以试试这个工具，我反正用的挺愉快的。

2016年5月31日火曜日、小樱<notifications@github.com>さんは書きました:
