### ISSUE TITLE
Deprecation notice

### ISSUE THREAD

**Issue by arilewis93** [sjitech/proxy-login-automator#23]
When running the script I get the following warning.

`DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.`

I don't know enough about node or JavaScript to know what to change to. I really look forward to using this, so help would be much appreciated

**Comment by jjqq2013** [comment]
hi do not worry, just ignore the warning. I will change it in later version.
