### ISSUE TITLE
Unexpected number for -local_port

### ISSUE THREAD

**Issue by Ahama1992** [sjitech/proxy-login-automator#25]
Dear sir/madam,
Just to be clear, I have very little knowledge on the subject. Here is a question.
I am trying to use this tool and I get the following error. 

The command line and the result:
![capture](https://user-images.githubusercontent.com/16062093/52256956-f740d880-292d-11e9-9eec-1b0c791b7cc1.PNG)

What is the problem?

**Comment by jjqq2013** [comment]
please run `node proxy-login-automator.js ...........` because `.js` by default will be run by another system program.

**Comment by Ahama1992** [comment]
Thank you so much for the response. You're a legend.
