### ISSUE TITLE
Error: getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by herlon214** [sjitech/proxy-login-automator#3]
I'm trying to execute your example and the result is: 

    Using parameters:
    {
      "local_host": "localhost",
      "local_port": 65000,
      "remote_host": "removed",
      "remote_port": 80,
      "usr": "removed",
      "pwd": "removed",
      "as_pac_server": true
    }
    Failed to listen at localhost:65000
    Error: getaddrinfo ENOTFOUND

**Comment by QianJin2013** [comment]
It seems localhost is not in your etc hosts. Try127.0.0.1 please
