### ISSUE TITLE
Proxy authentication prompt

### ISSUE THREAD

**Issue by apolymen** [sjitech/proxy-login-automator#4]
Hi,
I followed your instructions but when I try to open a site in a browser, I get a pop up asking for username/password. If I input correct domain\username & password, the pop up reappears.
My corporate proxy uses NTLMv2.

Any suggestions?

**Comment by QianJin2013** [comment]
I am sorry, it only support basic auth, does not support ntlmv2 currently. Maybe i forgot to mention it clearly in readme. It seems possible to support ntlmv2, i just have no time to do it now.

**Comment by apolymen** [comment]
Fair enough. Thank you.
