### ISSUE TITLE
Cortana doesn't work if proxy-login-automator is the default proxy

### ISSUE THREAD

**Issue by marceloguedes** [sjitech/proxy-login-automator#5]
If you setup proxy-login-automator to listen to localhost:8080 and configure the system to use this address as default proxy for all Windows 10, Cortana stops working, together with Windows Apps (like Weather). Everything else works fine, except Windows Apps and Cortana.

**Comment by QianJin2013** [comment]
thanks for your feedback. 

It seems the term "Windows Apps, like Weather" are *Universal Windows Apps*(UWP).

I'v heard about UWP that 
>the system proxy gets used by default and apps have the option of not going through the proxy."

(https://wpdev.uservoice.com/forums/110705-universal-windows-platform/suggestions/11323269--uwp-need-http-proxy-function)

So you can try to set UWP not use proxy.

Or, Maybe UWP are using other settings? You can try following ways to set proxy: 
http://www.digitalcitizen.life/how-set-proxy-server-windows-10

Good luck

**Comment by marceloguedes** [comment]
Thank you for the answer, but this doesn't work. The Proxy configuration through Windows Apps is the same as the proxy configuration through Internet Connection windowed application. If you change one, it change the another one. The netsh doesn't help too. It is quite a same I can't use proxy-login-automator for everything because of this issue. It is running in background in my system and used just for some applications.

Thank you for your time.

**Comment by QianJin2013** [comment]
Everyone works with Windows Store Apps should look at [Isolating Windows Store Apps on Your Network](https://technet.microsoft.com/en-us/itpro/windows/keep-secure/isolating-apps-on-your-network).

It seems Windows Store Apps have its own network policy such as how to connect to internet.
There are group policy "Computer Configuration\Policies\Administrative Templates\Network\Network Isolation\Internet proxy servers for apps" to serve these apps.

**Comment by QianJin2013** [comment]
Exactly, someone have already resolved this problem by above group policy settings.
See the last method of http://www.thewindowsclub.com/setup-proxy-metro-application-windows-8
