### ISSUE TITLE
[LocalProxy(:8081)][Connection to xx.xx.xx.xx:8080] Error: ended by remote peer

### ISSUE THREAD

**Issue by spectereye** [sjitech/proxy-login-automator#9]
Hello!
i tried it and got error above as shadowsocks forward proxy, i used putty for ssh also use the same proxy xx.xx.xx.xx:8080 and works, so i guess it use basic authorization, any suggestions? thanks!

**Comment by jjqq2013** [comment]
hi, you are right, this tool is using basic auth, it is a pitty.
<notifications@github.com>:

**Comment by jjqq2013** [comment]
I have modified source to mitigate the error "ended by remote peer" and ECONNRESET.
